//THIS IS THE MAIN STORE. HERE YOU MUST IMPORT ALL MODULES AND INSTANTIATE THE STORE WITH MODULES AND ANY ROOTSTATES AND ROOTTYPES
//FOR A GOOD ARTICLE ON HOW THIS WAS SETUP AND EXPLANATION SEE: https://codeburst.io/vuex-and-typescript-3427ba78cfa8

import Vue from 'vue';
//IMPORT VUEX AND STOREOPTIONS TO INIT STORE WITH ROOTSTATE TYPE
import Vuex, { StoreOptions } from 'vuex';
//IMPORT ROOTSTATE TYPE TO CONSTRAIN ANY PROPS IN THE ROOT(MAIN STORE) STATE. SO FOR EXAMPLE TO MAKE TYPE-SAFE THE VERSION VARIABLE IN THIS MAIN STORE.
import { RootState } from './types';
//BELOW IMPORT SPECIFIC MODULES TO BE ABLE TO INCLUDE THEM AS PART OF THE MAIN STORE. WE INCLUDE THE INDEX.TS FILE FOR EACH MODULE AS THERE WE IMPORT ALL THE DIFFERENT FUNCTIONALITY AS WELL AS TYPES
import { profile } from './profile/index';

Vue.use(Vuex);

const store: StoreOptions<RootState> = {
    //THESE WILL BE GLOBAL STATES
    state: {
        version: '1.0.0' // a simple property
    },
    //BELOW DEFINE ALL THE MODULES TO INCLUDE IN MAIN STORE.
    modules: {
        profile
    }
};

//INIT STORE. MAKE SURE TO ONLY DO IT ONCE HERE.  DO NOT INIT STORE EN IN INDEX.TS IT WILL CAUSE TYPE ERRORS.
export default new Vuex.Store<RootState>(store);